# Gradle
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Android
android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official

# CloudStream
cloudstream.repo=tamersariii/xcloudstream_tr_repo
